#ifndef MESHOPTIMIZER_H
#define MESHOPTIMIZER_H

#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Reduces the number of triangles in the mesh, attempting to preserve mesh appearance.
 * The algorithm tries to preserve mesh topology and can stop short of the target reduction ratio.
 *
 * destination must contain enough space for the resulting index buffer (index_count elements)
 * indices must contain index data that is the result of meshopt_generateVertexRemap
 * vertex_positions should have float3 position in the first 3 floats of each vertex
 *
 * options: 0 or meshopt_SimplifyLockBorder
 */
size_t meshopt_simplify(unsigned int* destination, const unsigned int* indices, size_t index_count, const float* vertex_positions, size_t vertex_count, size_t vertex_positions_stride, size_t target_index_count, float target_error, unsigned int options, float* result_error);

/**
 * Generates a vertex remap table from the vertex buffer and an optional index buffer and returns number of unique vertices
 * As a result, all vertices that are binary equivalent map to the same (new) location
 * It is recommended to specify the optional index buffer if it is present; this allows to handle non-manifold topology correctly
 */
size_t meshopt_generateVertexRemap(unsigned int* destination, const unsigned int* indices, size_t index_count, const void* vertices, size_t vertex_count, size_t vertex_size);

/**
 * Generates vertex buffer from the source vertex buffer and remap table generated by meshopt_generateVertexRemap
 *
 * destination must contain enough space for the resulting vertex buffer (unique_vertex_count elements, returned by meshopt_generateVertexRemap)
 * vertex_count should be the initial vertex count and not the value returned by meshopt_generateVertexRemap
 */
void meshopt_remapVertexBuffer(void* destination, const void* vertices, size_t vertex_count, size_t vertex_size, const unsigned int* remap);

/**
 * Generates index buffer from the source index buffer and remap table generated by meshopt_generateVertexRemap
 *
 * destination must contain enough space for the resulting index buffer (index_count elements)
 * indices can be NULL if the input is unindexed
 */
void meshopt_remapIndexBuffer(unsigned int* destination, const unsigned int* indices, size_t index_count, const unsigned int* remap);

enum {
    meshopt_SimplifyLockBorder = 1 << 0,
};

#ifdef __cplusplus
}
#endif

#endif
